### ISSUE TITLE
ENOENT jpegtran.exe in the vendor folder does not exists

### ISSUE THREAD

**Issue by manuel-di-iorio** [imagemin/imagemin-jpegtran#12]
I tried reinstalling jpegtran (even with --force) but the vendor folder in the node_modules/jpegtran-bin seems to not be installed for some reasons. In fact, when installing the plugin with npm, there is no "postinstall"
The error is thrown when running the gulp task with imagemin and jpegtran()

	Error in plugin 'gulp-imagemin:'
	Message:
		spawn myAppPath\node_modules\jpegtran-bin\vendor\jpeg
	tran.exe ENOENT
	Details:
		code: ENOENT
		errno: ENOENT
		syscall: spawn myAppPath\node_modules\jpegtran-bin\ve
	ndor\jpegtran.exe
		path:myAppPath\node_modules\jpegtran-bin\vendor\jpeg
	tran.exe
		spawnargs: -copy,none,-optimize,-progressive
		fileName: myFilenamePath

I'm on Windows 7 32bit

**Comment by manuel-di-iorio** [comment]
I tried manually putting the jpegtran.exe binary, downloaded from jpegclub.org/jpegtran
    
But now, I got this error:

	Error: write EPIPEE:\MyAppPath\node_modules\jpegtran-bin
	\vendor\jpegtran.exe: must name one input and one output file
	usage: MyAppPath\node_modules\jpegtran-bin\vendor\jpegtra
	n.exe [switches] inputfile outputfile
	Switches (names may be abbreviated):
        [list of commands etc..]

**Comment by manuel-di-iorio** [comment]
Ok I found the problem.
You have to do this on the console, after installing imagemin-jpegtran:

$ npm i jpegtrain-bin

You should write this on the readme.

PS: the path where you install this, must not have spaces or you will get an error "prebuild failed etc.. etc.."

**Comment by manuel-di-iorio** [comment]
Ok I found the problem.
You have to do this on the console, after installing imagemin-jpegtran:

    $ npm i jpegtrain-bin

You should write this on the readme.

PS: the path where you install this, must not have spaces or you will get an error "prebuild failed etc.. etc.."

**Comment by shinnn** [comment]
> You should write this on the readme.

We'll never. This project is tested on Windows and the problem like this don't happen. https://ci.appveyor.com/project/ShinnosukeWatanabe/imagemin-jpegtran

**Comment by manuel-di-iorio** [comment]
@shinnn  but it's happened to me.. I installed gulp-imagemin and it has installed imagemin-jpegtran. For some reasons, the postscript was not executed. As I wrote above, even installing imagemin-jpegtran manually with npm i imagetc.. the postscript was not executed. Only with the solution I found the jpegtran.exe was installed.

This problems comes even with optipng, so probably it's not really a issue with this plugin but obviously if someone have this problem does not know what to do..

**Comment by shinnn** [comment]
@manuel-di-iorio 

Can you show us the result of:

```
$ node --version
$ npm --version
$ npm ls imagemin imagemin-jpegtran jpegtran-bin
```

**Comment by manuel-di-iorio** [comment]
1) 5.0.0
2) 3.3.7
3)
E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool>npm ls imagemin imagemin-jpegtran jpegtran-bin
E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool
├─┬ gulp-imagemin@2.4.0
│ └── imagemin@4.0.0
├── imagemin-jpegtran@4.3.2
└── jpegtran-bin@3.0.6

**Comment by shinnn** [comment]
Also, Can you show us the entire log (not just error log) of `npm install imagemin-jpegtran`?

**Comment by manuel-di-iorio** [comment]
E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool>npm install imagemin-jpegtran
E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool
└── imagemin-jpegtran@4.3.2

^ this is the entire log

**Comment by shinnn** [comment]
Try `npm install -S imagemin-jpegtran` again after removing all the files and folders under `node_modules`.

**Comment by manuel-di-iorio** [comment]
E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool>npm install -S imagemin-jpegtran

> jpegtran-bin@3.0.6 postinstall E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool\node_modules\jp
egtran-bin
> node lib/install.js

'node' is not recognized as an internal or external command,
operable program or batch file.
E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool
├── is-jpg@1.0.0
└─┬ through2@2.0.0
  ├─┬ readable-stream@2.0.4
  │ ├── core-util-is@1.0.2
  │ ├── inherits@2.0.1
  │ ├── isarray@0.0.1
  │ ├── process-nextick-args@1.0.6
  │ ├── string_decoder@0.10.31
  │ └── util-deprecate@1.0.2
  └── xtend@4.0.1

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "I:\\Program Files\\nodejs\\node.exe" "I:\\Users\\Computer\\AppData\\Roaming\\npm\\nod
e_modules\\npm\\bin\\npm-cli.js" "install" "-S" "imagemin-jpegtran"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.7
npm ERR! code ELIFECYCLE

npm ERR! jpegtran-bin@3.0.6 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jpegtran-bin@3.0.6 postinstall script 'node lib/install.js'.
npm ERR! This is most likely a problem with the jpegtran-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls jpegtran-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\MyFiles\Manuel\Web\Node.JS\Utilities\WebAutoTool\npm-debug.log

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin-jpegtran/issues/12#issue-120114906

>  In fact, when installing the plugin with npm, there is no "postinstall"

That was wrong.

**Comment by shinnn** [comment]
Seems like an npm bug. https://github.com/npm/npm/issues/9947

**Comment by coco-napky** [comment]
This happened recently to me, I case anyone wants to fix this quickly, just do: npm rebuild jpegtran-bin

**Comment by toantd90** [comment]
I got the same issue and try to fix it in some ways, but still can not get out of this. 
Here is my question on StackOverflow. Can anyone help me?
[gulp-imagemin jpegtran-bin does not work](https://stackoverflow.com/questions/44298119/gulp-imagemin-jpegtran-bin-does-not-work-when-i-run-the-simple-task)

**Comment by shinnn** [comment]
This is not an imagemin-jpegtran issue, at least.
