### ISSUE TITLE
"read ECONNRESET" when running with some large JPEGs

### ISSUE THREAD

**Issue by bjester-ss** [imagemin/imagemin-jpegtran#13]
When using the attached image with `imagemin`, I get a `read ECONNRESET` that's coming from the jpegtran child process created in this module. I've spent some time looking at this, and haven't really figured out why this is happening. I commented out [this error handling](https://github.com/imagemin/imagemin-jpegtran/blob/master/index.js#L61) and made a change to `through2` to let it write the file. The output file ends up intact, despite the error, and has the same md5sum as running the image manually through the `jpegtran` vendor binary. Also, when manually running the vendor binary, it exits without error.
```
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

![_dsc1100](https://cloud.githubusercontent.com/assets/2325472/12791135/76a15bbc-ca5a-11e5-8bc3-803a6900c29f.JPG)

**Comment by shinnn** [comment]
Cannot confirm on my Mac OS X 10.11.3.

* Which OS?
* Node/npm/imagemin-jpegtran version?

**Comment by bjester-ss** [comment]
@shinnn This happened on:
- Fedora 20 and AWS Lambda (using same files from Fedora)
- Node 0.10 and 0.12
- NPM 2.14

It happened with the latest `imagemin` (and older versions), which installed `imagemin-jpegtran` 4.3.2

**Comment by shinnn** [comment]
@bjester-ss Do you need to pin your Node and npm to those ancient versions? I often hear that upgrading Node to the latest version solved the problems perfectly. https://github.com/imagemin/imagemin/issues/133#issuecomment-152750841

**Comment by bjester-ss** [comment]
@shinnn Unfortunately, AWS Lambda only runs Node version 0.10.

**Comment by shinnn** [comment]
Now [Node v4 is available on Lambda](https://aws.amazon.com/jp/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/) and this issue will be fixed if you upgrade to Node v4.

@bjester-ss Feel free to comment more if Node v4 still doesn't solve the problem.
