### ISSUE TITLE
imagemin-jpegtran 5.0.0

### ISSUE THREAD

**Issue by Vadizar** [imagemin/imagemin-jpegtran#15]
After update imagemin-jpegtran 5.0.0 not working:
/Users/MobiDevices/Work/1000.tech/node_modules/readable-stream/lib/_stream_readable.js:740
  stream.on('end', function () {
         ^

TypeError: stream.on is not a function

**Comment by shinnn** [comment]
https://github.com/imagemin/imagemin/issues/164#issuecomment-216126624
