### ISSUE TITLE
bump jpegtran-bin to 6.0.0

### ISSUE THREAD

**Issue by BigMichi1** [imagemin/imagemin-jpegtran#35]
pls bump version of jpegtran-bin to 6.0.0

see https://github.com/imagemin/jpegtran-bin/pull/101

**Comment by Levdbas** [comment]
Hi @sindresorhus, would you mind taking this update in consideration and release a patched version of imagemin-jpegtran? Thank you for your time in advance!

**Comment by fmagaldea** [comment]
👍 
It would be great if any manager of this project could upgrade this dependency?

**Comment by timmywil** [comment]
upgrading jpegtran-bin to 6-7+ would also fix the security vulnerability.
