### ISSUE TITLE
npm ERR! https://npm.taobao.org/mirrors/jpegtran-bin/v6.0.0/vendor/

### ISSUE THREAD

**Issue by lnjdsg** [imagemin/imagemin-jpegtran#42]
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! https://npm.taobao.org/mirrors/jpegtran-bin/v6.0.0/vendor/
npm ERR! compiling from source
npm ERR! certificate has expired
npm ERR! jpegtran pre-build test failed

**Comment by shenhao98** [comment]
老哥 你写代码是一点英文也不会吗？
