### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by davetgreen** [imagemin/imagemin-jpegtran#5]
I'm getting this error on a Windows 7 32 bit machine:

> node lib/install.js

  ‼ spawn ENOENT
  ‼ jpegtran pre-build test failed
  i compiling from source
  × Error: Command failed: '.' is not recognized as an internal or externa
and,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
imagemin-jpegtran@4.0.0 node_modules\imagemin-jpegtran
├── is-jpg@1.0.0
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
└── jpegtran-bin@2.0.2 (logalot@2.1.0, bin-build@2.1.0, bin-wrapper@2.1.3)

Cheers,
Dave

**Comment by kevva** [comment]
Should work fine on Windows, at least on 64 bit.

![asd](https://cloud.githubusercontent.com/assets/709159/5722863/2599e6e8-9b40-11e4-89e7-12b406bf836d.png)

**Comment by davetgreen** [comment]
Is there anything I can do to dig a little deeper and find out more about what is causing this? We're really keen to get imagemin into our workflow :)

Cheers,
Dave

**Comment by kevva** [comment]
Did you receive any errors upon installation?
