### ISSUE TITLE
Builds using imagemin breaking since 4.2.0

### ISSUE THREAD

**Issue by mattdrose** [imagemin/imagemin-jpegtran#6]
For the last couple days, all my builds that require grunt-contrib-image@0.9.2 have been failing due to the following warning:

```
Warning: Error: Error: write EPIPE/var/data/atlassian/application-data/bamboo/xml-data/build-dir/DSP-JOB1/web/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/data/atlassian/application-data/bamboo/xml-data/build-dir/DSP-JOB1/web/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor/jpegtran)
```

I'm wondering if it's due to the 4.2.0 bump. Any ideas?

Thanks!

**Comment by tmirks** [comment]
+1

**Comment by kevva** [comment]
Might be related. Could you try upgrading your `libc6` version?

**Comment by tmirks** [comment]
Hey @kevva, we are using CentOS 6 and are unable to upgrade libc!

Any other suggestions?

**Comment by mattdrose** [comment]
Thanks @tmirks,

Also, rolling back to `4.1.0` fixed the issue for me.

`4.2.0` doesn't seem to be fully backwards compatible. Not sure if others are running into this issue.

**Comment by charliegeiger89** [comment]
+1

Unable to upgrade libc6 on CentOS 6. Had to traverse from gulp-imagemin down to imagemin-jpegtran and change version.

**Comment by tmirks** [comment]
@charliegeiger89 See my previous comment -- it works if you install NASM.

**Comment by charliegeiger89** [comment]
Issue appears to have been fixed with latest jpegtran-bin / imagemin-jpegtran.
