### ISSUE TITLE
enabling progressive and arithmetic features causes jpegtran to throw an unhelpful error.

### ISSUE THREAD

**Issue by chris-t-reilly** [imagemin/imagemin-jpegtran#7]
Using progressive and arithmetic features together raises this error: 

`Error: Requested feature was omitted at compile time`

Would you accept a pull request to either work around this or to raise a more meaningful error?

**Comment by chris-t-reilly** [comment]
Appears to be related to this problem with jpegtran is comiled: http://comments.gmane.org/gmane.comp.graphics.libjpeg-turbo.user/143

**Comment by sindresorhus** [comment]
:+1: PR welcome :)
