### ISSUE TITLE
imagemin-jpegtran broken pipe

### ISSUE THREAD

**Issue by oscarmcm** [imagemin/imagemin-jpegtran#8]
Note:
   * I'm using gulp and gulp-imagemin

This is my gulp task:

```js
// Optimize Images
gulp.task('images', function () {
  return gulp.src('app/images/**/*')
    .pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true
    })))
    .pipe(gulp.dest('dist/images'))
    .pipe($.size({title: 'images'}));
});
```

And this is my stack trace:

```
Unhandled rejection Error: Error: write EPIPE
    at ChildProcess.<anonymous> (/Users/oscarmcm/Code/html/sHyrax/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/index.js:60:11)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by mrnix** [comment]
+1

**Comment by oscarmcm** [comment]
It's seem a bug with only jpeg images

**Comment by mrnix** [comment]
Now I'm using `imagemin-mozjpeg` plugin instead, it works without errors

**Comment by shinnn** [comment]
I just edited the markup of @oscarmcm's comment. https://github.com/imagemin/imagemin-jpegtran/issues/8#issue-103310470

Correct [markdown syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) helps the maintainers read your code.

**Comment by shinnn** [comment]
@oscarmcm @mrnix Can you create a small repository that can reproduce the problem?

**Comment by shinnn** [comment]
https://github.com/sindresorhus/gulp-imagemin/issues/142#issue-110802779

> ![pizzeria](https://cloud.githubusercontent.com/assets/8584904/10412024/fa38bdd6-6f46-11e5-98e8-219df12c5e6e.jpg)
> 
> The console error output states:
> events.js:85 throw er; //Unhandled 'error' event
> 
> Error: Error: write EOF
>     at ChildProcess.<anonymous> (FILEPATH\imagemin-jpegtran\index.js:60:11)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1015:16)
>     at Socket.<anonymous> (child_process.js:1183:11)
>     at Socket.emit (events.js:107:17)
>     at Pipe.close (net.js:485:12)
>

**Comment by oscarmcm** [comment]
:+1: thanks @shinnn

**Comment by dmullings81** [comment]
I have a similar issue to the one above. I opened the issue in imagemin [here ](https://github.com/sindresorhus/gulp-imagemin/issues/158)
Many thanks.

**Comment by shinnn** [comment]
* Which OS?
* Node/npm/imagemin/imagemin-jpegtran version?

**Comment by dmullings81** [comment]
Windows Vista SP2 (I know)
Node 4.3.0
NPM 2.14.12
imagemin 2.4.0
imagemin-jpegtran ^4.3.2

**Comment by shinnn** [comment]
> imagemin 2.4.0

Really ancient version. Upgrade to the latest imagemin and try again.

**Comment by dmullings81** [comment]
Thanks, that's solved it. No idea why it was such an old version.

**Comment by shinnn** [comment]
No problem.
